CRITICAL - 2022-03-09 05:46:45 --> syntax error, unexpected 'f' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
#0 C:\xampp\htdocs\smrpo\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\smrpo\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 C:\xampp\htdocs\smrpo\app\Controllers\Home.php(5): spl_autoload_call('App\\Controllers...')
#4 C:\xampp\htdocs\smrpo\system\Autoloader\Autoloader.php(264): include_once('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\smrpo\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\smrpo\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#7 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#8 [internal function]: spl_autoload_call('App\\Controllers...')
#9 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(797): class_exists('\\App\\Controller...', true)
#10 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(406): CodeIgniter\CodeIgniter->startController()
#11 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\smrpo\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-03-09 06:35:05 --> Call to undefined function set_value()
#0 C:\xampp\htdocs\smrpo\system\View\View.php(210): include()
#1 C:\xampp\htdocs\smrpo\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\smrpo\system\Common.php(1089): CodeIgniter\View\View->render('admin/userCreat...', Array, true)
#3 C:\xampp\htdocs\smrpo\app\Controllers\UsersController.php(24): view('admin/userCreat...', Array)
#4 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(832): App\Controllers\UsersController->registerUserForm()
#5 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsersController))
#6 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\smrpo\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-03-09 07:25:55 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-03-09 07:25:55 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\smrpo\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\smrpo\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\smrpo\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\smrpo\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\smrpo\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\smrpo\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\smrpo\app\Controllers\UsersController.php(37): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(832): App\Controllers\UsersController->createUser()
#8 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsersController))
#9 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\smrpo\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-09 07:29:25 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-03-09 07:29:25 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\smrpo\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\smrpo\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\smrpo\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\smrpo\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\smrpo\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\smrpo\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\smrpo\app\Controllers\UsersController.php(37): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(832): App\Controllers\UsersController->createUser()
#8 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsersController))
#9 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\smrpo\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-09 07:33:55 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-03-09 07:33:55 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\smrpo\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\smrpo\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\smrpo\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\smrpo\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\smrpo\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\smrpo\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\smrpo\app\Controllers\UsersController.php(37): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(832): App\Controllers\UsersController->createUser()
#8 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsersController))
#9 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\smrpo\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-09 07:34:03 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-03-09 07:34:03 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\smrpo\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\smrpo\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\smrpo\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\smrpo\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\smrpo\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\smrpo\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\smrpo\app\Controllers\UsersController.php(37): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(832): App\Controllers\UsersController->createUser()
#8 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsersController))
#9 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\smrpo\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-09 07:39:08 --> No database selected
CRITICAL - 2022-03-09 07:39:08 --> No database selected
#0 C:\xampp\htdocs\smrpo\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\smrpo\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\smrpo\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\smrpo\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\smrpo\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\smrpo\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\smrpo\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\smrpo\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\smrpo\app\Controllers\UsersController.php(37): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(832): App\Controllers\UsersController->createUser()
#10 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsersController))
#11 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\smrpo\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2022-03-09 07:48:24 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-03-09 07:48:24 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\smrpo\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\smrpo\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\smrpo\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\smrpo\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\smrpo\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\smrpo\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\smrpo\app\Controllers\UsersController.php(37): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(832): App\Controllers\UsersController->createUser()
#8 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsersController))
#9 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\smrpo\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-03-09 08:07:06 --> Cannot redeclare App\Controllers\UsersController::login()
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-09 08:07:29 --> Undefined variable: data
#0 C:\xampp\htdocs\smrpo\app\Controllers\UsersController.php(56): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 56, Array)
#1 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(832): App\Controllers\UsersController->login()
#2 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsersController))
#3 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\smrpo\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-03-09 08:07:40 --> Call to undefined function set_value()
#0 C:\xampp\htdocs\smrpo\system\View\View.php(210): include()
#1 C:\xampp\htdocs\smrpo\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\smrpo\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#3 C:\xampp\htdocs\smrpo\app\Controllers\UsersController.php(60): view('login', Array)
#4 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(832): App\Controllers\UsersController->login()
#5 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsersController))
#6 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\smrpo\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-03-09 08:38:01 --> Class 'App\Controllers\BaseController' not found
#0 C:\xampp\htdocs\smrpo\system\Router\Router.php(518): include_once()
#1 C:\xampp\htdocs\smrpo\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('/')
#2 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(726): CodeIgniter\Router\Router->handle('/')
#3 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#4 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\smrpo\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-03-09 13:17:18 --> validateUser is not a valid rule.
#0 C:\xampp\htdocs\smrpo\system\Validation\Validation.php(300): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('validateUser')
#1 C:\xampp\htdocs\smrpo\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'ss', Array, Array)
#2 C:\xampp\htdocs\smrpo\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#3 C:\xampp\htdocs\smrpo\app\Controllers\UsersController.php(67): CodeIgniter\Controller->validate(Array, Array)
#4 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(832): App\Controllers\UsersController->login()
#5 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsersController))
#6 C:\xampp\htdocs\smrpo\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\smrpo\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
